# Generated by Django 5.2.4 on 2025-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
